#!/usr/bin/env sh

# Unload the macOS WindowManager process
# launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
# yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"

# yabai -m config layout bsp

yabai -m config top_padding    5
yabai -m config bottom_padding 5
yabai -m config left_padding   5
yabai -m config right_padding  5
yabai -m config window_gap     5

# yabai -m config window_shadow float
# yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0
# yabai -m config window_topmost on

yabai -m config window_border on
yabai -m config window_border_width 1
yabai -m config active_window_border_color 0xFF88C0D0
yabai -m config normal_window_border_color 0x002E3440

yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off





